### ISSUE TITLE
Typo in "https://github.com/alexandre-khoury/blog/tree/main/posts/docker-nftables/README.md"

### ISSUE THREAD

**Issue by Shea690901** [alexandre-khoury/blog#1]
I googled for "docker" and "nft" and found among others your blog. But sadly I also found a typo:
In Section "Docker configuration", Subsection "Networking prerequisites" you give the possible private networks, among them:
```127.17.0.0/12```
Better would be:
```172.17.0.0/12``` 😉

Otherwise thanks for the info 🙂

P.S.:
And don't forget:
```172.17.0.0/12``` is identical to ```172.16.0.0/12``` (I nearly did)

**Comment by alexandre-khoury** [comment]
Thank you very much for this useful feedback, you're definitely right
